### ISSUE TITLE
Needs updated instructions.

### ISSUE THREAD

**Issue by bordencastle** [ansible-lockdown/RHEL7-STIG-Audit#15]
1. run_audit.sh makes assumptions on paths that would be better if parameterized with the run_audit.sh command.
2. run_audit.sh does not pick up the timeout variable by itself. Checks default to a 1 second time, and 50% fail with the 1 second timeout.
3. If you run just the goss.yml, it complains about machine_uuid, so seems the only option is to use the run_audit.sh script.
4. The benchmark_version in /vars/STIG.yml is set to 3.5, but the version in the instructions is 3.6.

**Comment by bordenit** [comment]
Two of the configurable parameters could be to set the max-concurrent tests for goss and to set the output format for goss in the run_audit.sh file. Outputting in Junit might be worthwhile when the tests are published.

**Comment by bordenit** [comment]
@uk-bolly That looks promising. Will test it tomorrow. For 1, no big deal, just took a little more love to move the files around. Got used to just cloning or downloading zips with paths being $(pwd), ./ or in case of Ansible {{ playbook_dir }} in the scripts.

**Comment by uk-bolly** [comment]
hi @bordenit 

Ive added a couple of format layouts to the script in the issue_15 branch. This should now work with junit, rspecish, tap, documentation and json.
Hope this is what you are referring too?

Thanks

uk-bolly

**Comment by bordenit** [comment]
@uk-bolly Thanks. Will test soon.

**Comment by bordenit** [comment]
The json output works. Still some issues with it timing out, but for the original request the ticket can be closed.
